USE ROLE ACCOUNTADMIN;

-- Create Database and Schemas to separate processing, execution, and deployment
CREATE DATABASE IF NOT EXISTS ML_SNOWPARK_CI_CD;
USE DATABASE ML_SNOWPARK_CI_CD;
CREATE SCHEMA IF NOT EXISTS DATA_PROCESSING;
CREATE SCHEMA IF NOT EXISTS ML_PROCESSING;


-- Create a test UDF
CREATE OR REPLACE FUNCTION DATA_PROCESSING.MULTIPLY(X NUMBER(35,4), Y NUMBER(35,4))
RETURNS NUMBER(35,4)
    AS
$$
    X  * Y
$$;

select DATA_PROCESSING.MULTIPLY(499, 599) as product;